MVCReports/MVCReports/Controllers/RoleController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using MVCReports.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCReports.Controllers
{
    public class RoleController : Controller
    {

        private ApplicationDbContext context;
        
        public RoleController()
        {
            context = new ApplicationDbContext();
        }


        // GET: Role
        public ActionResult Index()
        {
            var roles = context.Roles.ToList();
            var users = context.Users.ToList();
            
            return View(roles);
        }

        public ActionResult Create()
        {
            var role = new IdentityRole();
            return View(role);
        }

        [HttpPost]
        public ActionResult Create(IdentityRole role)
        {
            context.Roles.Add(role);
            context.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

MVCReports/MVCReports/Controllers/UserController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using MVCReports.Context;
using MVCReports.Helpers;
using MVCReports.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCReports.Controllers
{
    public class UserRoleController : Controller
    {
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationDbContext context;
        private EntityContext db;

        public UserRoleController()
        {
            context = new ApplicationDbContext();
            db = new EntityContext();
        }

        // GET: User
        public async Task<ActionResult> Index()
        {
            var userList = new List<UserWithRole>();
            var users = context.Users.ToList();

            var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));

            foreach (var u in users)
            {
                var user = new UserWithRole();
                user.UserName = u.UserName;
                user.Email = u.Email;
                user.PhoneNumber = u.PhoneNumber;
                user.Id = u.Id;

                if (u.Roles.Count == 0)
                    user.Role = "";
                else
                {
                    var role = await RoleManager.FindByIdAsync(u.Roles.First().RoleId);
                    user.Role = role.Name;
                }
                userList.Add(user);
            }         
            return View(userList);
        }

        public ActionResult ModifyRole(string id)
        {

            if (id == null || id == "")
            {
                return RedirectToAction("Index");
            }
            // to do check if id is not null 
            var u = context.Users.Where(us => us.Id == id).FirstOrDefault();
            var user = new UserWithRole();
            user.UserName = u.UserName;
            user.Email = u.Email;
            user.PhoneNumber = u.PhoneNumber;
            user.Id = u.Id;

            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View(user);
        }
        
        [HttpPost]
        public async Task<ActionResult> ModifyRole(string id, string roles)
        {
            var user = UserManager.Users.Where(u => u.Id.Equals(id)).ToList()[0];

            if (user.Roles.Count > 0) {
                var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
                var role = await RoleManager.FindByIdAsync(user.Roles.First().RoleId);
                UserManager.RemoveFromRole(id, role.Name);
            }

            await UserManager.AddToRoleAsync(id, roles);
            return RedirectToAction("index");
        }

        public ActionResult AssingProjectToUser(string userName)
        {
            var projectList = new Dictionary<string, List<Customer>>();                              
           
            projectList.Add("Pie",ConstructCustomerList("Pie", userName));
            projectList.Add("Stacked", ConstructCustomerList("Stacked", userName));
            projectList.Add("Accuracy", ConstructCustomerList("Accuracy", userName));

            var assignedProjects= new AssignedProjectModel() { AssignedProject = projectList, UserName = userName };

            return View(assignedProjects);
        }

        private List<Customer> ConstructCustomerList(string table, string userName)
        {
            var list = new List<Customer>();

            var dbService = new DatabaseService();
            var customers = dbService.GetList(table);

            var userProjects = db.UserProject.Where(e => e.UserName == userName && e.Type == table).Select(e => e.CustomerName).ToList();

            foreach(var c in customers)
            {
                var customer = new Customer { Checked = false, Name = c };
                
                if(userProjects.Contains(c))
                {
                    customer.Checked = true;
                }

                list.Add(customer);
            }


            return list;
        }

        [HttpPost]
        public ActionResult AssingProjectToUser(AssignedProjectModel projects)
        {
            var userProjects = db.UserProject.Where(e => e.UserName == projects.UserName);

            foreach (var p in userProjects)
            {
                db.UserProject.Remove(p);
            }

           

            foreach(var pair in projects.AssignedProject)
            {
                foreach(var item in pair.Value)
                {
                    if(item.Checked)
                    {
                        db.UserProject.Add(new UserProjectsModel { CustomerName = item.Name, Type = pair.Key, UserName = projects.UserName });
                        db.SaveChanges();
                    }
                }
            }

            return RedirectToAction("index");
        }
    }
}

MVCReports/MVCReports/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,500,700,300' rel='stylesheet' type='text/css'>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{ var  role = System.Web.HttpContext.Current.Session["role"];}
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Report App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @Html.Partial("_LoginPartial")
            @if (role != null)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        @if (role.ToString().Equals("Admin"))
                        { 
                            <li>@Html.ActionLink("Management", "Index", "UserRole")</li>
                            @*<li class=" dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Management <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("User Role", "Index", "UserRole")</li>
                                    <li>@Html.ActionLink("User Role", "AssingProjectToUser", "UserRole")</li>
                                </ul>
                            </li>*@
                        }
                        @*<li>@Html.ActionLink("Roles", "index", "Role")</li>*@
                        @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    </ul>

                </div>
            }
        </div>
    </div>
@if (role != null&& !Request.Path.Contains("UserRole"))
{
    <div class="navbar navbar-inverse tabs">
        <div class="container">
            <div class="navbar-inner">
                <ul class="nav navbar-nav" id="report-type-list">
                @if (role.ToString().Equals("Admin"))
                {
                    <li class="@(ViewBag.Type == "Email" ? "active" : "")">@Html.ActionLink("Email Office", "Index", "Home", new { reportType = "Email" }, new { name = "Email" })</li>
                }
                    <li class="@(ViewBag.Type == "Pie"?"active" : "")">@Html.ActionLink("Pie Chart", "Index", "Home", new { reportType = "Pie" }, new { name = "Pie" })</li>
                    <li class="@(ViewBag.Type == "Accuracy"?"active" : "")">@Html.ActionLink("Accuracy Statistik", "Index", "Home", new { reportType = "Accuracy" }, new { name = "Accuracy" })</li>
                    <li class="@(ViewBag.Type == "Stacked"?"active" : "")">@Html.ActionLink("Stacked", "Index", "Home", new { reportType = "Stacked" }, new { name = "Stacked" })</li>
                </ul>
            </div>
        </div>
     </div>
}
    <div class="container body-content">
        @RenderBody()
    </div>  
        <footer>

            
                <p>&copy; @DateTime.Now.Year - Recall</p>
 

            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>